services:
  dbtodo:
    image: postgres:16
    container_name: droplets_todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    # ports:
    #   - "6601:5432" # - note: host port is changed to not have conflict with the other docker-compose

    
    networks:
      - tododb_network


networks:
  tododb_network:
    external: true
