services:

  
  db_history:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: droplet_historydb
    ports:
      - "5433:5432" # - note: host port is changed to not have conflict with the other docker-compose

    
    networks:
      - history_network


networks:
  history_network:
    external: true
