services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile.app
    env_file:
      - ./app/.docker.env
    
    networks:
      - app_network
      - event_network



networks:
  app_network:
    external: true

  event_network:
    external: true
