services:
  dbtodo: # no volume - won't presist after shutdown
    image: postgres:16
    container_name: droplets_todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    # ports:
    #   - "6601:5432" # - note: host port is changed to not have conflict with the other docker-compose

    
    networks:
      - tododb_network
  

  dbhistory: # no volume - won't presist after shutdown
    image: postgres:16
    container_name: droplets_history_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: history_db
    # ports:
    #   - "6601:5432" # - note: host port is changed to not have conflict with the other docker-compose

    
    networks:
      - historydb_network
    
  
  dbevent: # no volume - won't presist after shutdown
    image: postgres:16
    container_name: droplets_event_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: event_db
    # ports:
    #   - "6601:5432" # - note: host port is changed to not have conflict with the other docker-compose

    
    networks:
      - eventdb_network
  

  kafka:
    image: apache/kafka:4.3.1
    container_name: droplets_kafka

    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

    networks:
      - event_network


  kafka-init:
    image: apache/kafka:4.3.1
    container_name: droplets_kafka_init

    depends_on:
      - kafka

    command:
      - /bin/sh
      - -c
      - |
        echo "Waiting for Kafka..."

        until /opt/kafka/bin/kafka-topics.sh --bootstrap-server kafka:9092 --list >/dev/null 2>&1
        do
          sleep 1
        done

        echo "Kafka is ready"

        echo "Creating tasks topic..."
        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic tasks \
          --partitions 1 \
          --replication-factor 1

        echo "Creating tasks.dlq topic..."
        /opt/kafka/bin/kafka-topics.sh \
          --bootstrap-server kafka:9092 \
          --create \
          --if-not-exists \
          --topic tasks.dlq \
          --partitions 1 \
          --replication-factor 1

        echo "Kafka initialization complete"

    networks:
      - event_network


networks:
  tododb_network:
    external: true
  historydb_network:
    external: true
  event_network:
    external: true
  eventdb_network:
    external: true