services:
  history:
    build:
      context: .
      dockerfile: docker/Dockerfile.history
    container_name: droplets_history
    
    env_file:
      - ./services/history/.docker.env
    # ports:
    #   - "5501:5501"
    
    networks:
      - event_network
      - gateway_network
      - historydb_network



networks:
  gateway_network:
    external: true
  historydb_network:
    external: true
  event_network:
    external: true

