services:
  dbtodo: # no volume - won't presist after shutdown
    image: postgres:16
    container_name: droplets_todo_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo_db
    # ports:
    #   - "6601:5432" # - note: host port is changed to not have conflict with the other docker-compose

    
    networks:
      - tododb_network
  

  dbhistory: # no volume - won't presist after shutdown
    image: postgres:16
    container_name: droplets_history_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: history_db
    # ports:
    #   - "6601:5432" # - note: host port is changed to not have conflict with the other docker-compose

    
    networks:
      - historydb_network
  

  kafka: # no volume - won't presist after shutdown
    image: apache/kafka:4.3.1
    container_name: droplets_kafka
    # ports:
    #   - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller

      KAFKA_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092

      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    
    networks:
      - event_network


networks:
  tododb_network:
    external: true
  historydb_network:
    external: true
  event_network:
    external: true