services:
  dbhistory:
    image: postgres:16
    container_name: droplets_history_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: history_db
    # ports:
    #   - "6601:5432" # - note: host port is changed to not have conflict with the other docker-compose

    
    networks:
      - historydb_network


networks:
  historydb_network:
    external: true
