services:
  nats:
    image: nats:2
    command: ["-js", "-m", "8222"]
    ports:
      - "4222:4222"
      - "8222:8222"
    networks:
      - event_network

networks:
  event_network:
    external: true
