services:
  gateway:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: droplets_gateway
    env_file:
      - .docker.env
    ports:
      - "5500:5500"
    networks:
      - gateway_network



networks:
  gateway_network:
    external: true

