CREATE TABLE IF NOT EXISTS todo_model (
    id BIGSERIAL PRIMARY KEY,
    value TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
