CREATE TABLE IF NOT EXISTS task_model (
    id BIGSERIAL PRIMARY KEY,
    pid TEXT UNIQUE NOT NULL,
    value TEXT NOT NULL,
    completed BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);
