# ----------------------------BUILD STAGE ----------------------- #
FROM golang:1.26 AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o /dist ./services/history/cmd/web/

# ----------------------------RUN STAGE ----------------------- #
FROM ubuntu:24.04
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends ca-certificates && rm -rf /var/lib/apt/lists/*
COPY --from=builder /dist /app/dist
COPY ./services/history/migrations /app/migrations
CMD ["./dist"]