services:
  event:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: droplets_event
    
    env_file:
      - .docker.env
    
    networks:
      - event_network
      - eventdb_network
      - historydb_network



networks:
  event_network:
    external: true
  eventdb_network:
    external: true
  historydb_network:
    external: true